------------------------------관리자 테이블 생성------------------------------- 부모!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DROP TABLE ADMIN cascade Constraints;
CREATE TABLE ADMIN(          
    AID VARCHAR2(10) PRIMARY KEY,
    APW VARCHAR2(10) NOT NULL
    );

INSERT INTO ADMIN VALUES('AA','AA');


 --------------------------------회원등급----------------------------------//부모!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DROP TABLE MEMBERGRADE cascade Constraints;
CREATE TABLE MEMBERGRADE(
    MLEVELNO NUMBER(2) PRIMARY KEY,
    MLEVELNAME VARCHAR2(30),
    MLEVELDC float(10)
    );
    select * from product;
update product set pstock =10000;
commit;
Insert into MemberGrade values(0,'a',0.00);
Insert into MemberGrade values(1,'b',0.02);
Insert into MemberGrade values(2,'c',0.04);
Insert into MemberGrade values(3,'d',0.05);

 --------------------------------제품----------------------------------//부모!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DROP TABLE PRODUCT cascade Constraints;
DROP SEQUENCE PRODUCT_SEQ;
Create Sequence PRODUCT_SEQ;
CREATE TABLE PRODUCT(
    PID VARCHAR2(30) PRIMARY KEY,
    PNAME VARCHAR2(30) NOT NULL,
    PCAL NUMERIC(5),
    PMEGAPICK NUMERIC(1),
    PMDPICK NUMERIC(1),
    PMAIN VARCHAR2(20),
    PSTOCK NUMERIC(5),
    PPRICE NUMERIC(6),
    PCONTENT VARCHAR2(1000),
    PRATE NUMERIC(2),
    PIMAGE VARCHAR2(50) DEFAULT 'NOIMAGE.PNG',
    PHIREDATE DATE DEFAULT SYSDATE,
    PHIT NUMERIC(9)
    );
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '버섯 곤드레', 150, '미역', 25000, '전태경미역', 0,'버섯 곤드레.png',1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '오리 월남쌈', 500, '고추', 25000, '매콤한', 30,'오리 월남쌈.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소이냉파스타', 800, '메밀', 25000, '시원한메밀', 38,'소이냉파스타.png',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '퀘사디아', 800, '잡지', 25000, '이제훈이 요리하는 레시피잡지', 38,'퀘사디아.png',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기 월남쌈', 500, '고추', 25000, '매콤한', 30,'오리 월남쌈.jpg',100,1);
select * from PRODUCT;
DESC PRODUCT;
commit;
SELECT * FROM PRODUCT WHERE PMEGAPICK=1;
------------------------------회원 테이블 생성------------------------------- 
DROP TABLE MEMBER cascade Constraints;
CREATE TABLE MEMBER(      
    MID VARCHAR2(20) PRIMARY KEY,
    MPW VARCHAR2(10) NOT NULL,
    MBLOCK NUMERIC(2) DEFAULT 0,
    MNAME VARCHAR2(20) NOT NULL,
    MGENDER VARCHAR2(10),
    MTEL VARCHAR2(20),
    MEMAIL VARCHAR2(50),
    MPOSTNUM VARCHAR2(20),
    MADDRESS VARCHAR2(200),
    MJOINDATE DATE DEFAULT SYSDATE,   
    MTOTAL NUMERIC(10),
    MLEVELNO NUMERIC(2),
    FOREIGN KEY (MLEVELNO) REFERENCES MEMBERGRADE(MLEVELNO)
    );
    

 --------------------------------공지사항게시판----------------------------------
DROP TABLE NBOARD cascade Constraints;
CREATE TABLE NBOARD(          
    NBNO NUMBER(5) PRIMARY KEY,
    AID VARCHAR2(10),
    NBTITLE VARCHAR2(200) NOT NULL,
    NBCONTENT VARCHAR2(1000),
    NBHIT NUMERIC(4) NOT NULL,
    NBFILE VARCHAR2(50),
    NBTIME DATE DEFAULT SYSDATE,
    FOREIGN KEY (AID) REFERENCES ADMIN(AID)
    );

INSERT INTO NBOARD VALUES(1,'AA','첫 번째 공지사항','아직 아무내용 없어',0,'DD',SYSDATE);

----------------------------------리뷰게시판----------------------------------- 
DROP TABLE RBOARD cascade Constraints;
drop sequence RBOARD_SEQ;
create sequence RBOARD_SEQ;

CREATE TABLE RBOARD(              
    RBNO NUMBER(5) PRIMARY KEY,
    AID VARCHAR2(10),
    MID VARCHAR2(20),
    RBTITLE VARCHAR2(100) NOT NULL,
    RBCONTENT VARCHAR2(1000) NOT NULL,
    RBHIT NUMERIC(4) NOT NULL,
    RBFILE VARCHAR2(50),
    RBREF NUMERIC(3),
    RBSTEP NUMERIC(3),
    RBLEVEL NUMERIC(3),
    RBTIME DATE DEFAULT SYSDATE,
    FOREIGN KEY (AID) REFERENCES ADMIN(AID),
    FOREIGN KEY (MID) REFERENCES MEMBER(MID)
    );
SELECT * FROM (
SELECT ROWNUM RN, A.*
    FROM (SELECT RBHIT, M.MID, M.MPW FROM RBOARD r, MEMBER M WHERE R.MID=M.MID ORDER BY RBHIT DESC) a)
        WHERE RN <=5;
INSERT INTO
		RBOARD(RBNO,MID, RBTITLE, RBCONTENT, RBFILE, RBREF, RBSTEP, RBLEVEL,RBHIT)
		VALUES(RBOARD_SEQ.NEXTVAL,'TT','뭐야','rbcontent','rbfile',RBOARD_SEQ.CURRVAL,0,0,0);
        commit;
--------------------------------Q&A게시판---------------------------------     
DROP TABLE QBOARD cascade Constraints;
DROP SEQUENCE QBOARD_SEQ;
CREATE SEQUENCE QBOARD_SEQ;
CREATE TABLE QBOARD(              
    QBNO NUMBER(5) PRIMARY KEY,
    AID VARCHAR2(10),
    MID VARCHAR2(20),
    QBTITLE VARCHAR2(100) NOT NULL,
    QBCONTENT VARCHAR2(1000) NOT NULL,
    QBHIT NUMERIC(4) NOT NULL,
    QBFILE VARCHAR2(50),
    QBREF NUMERIC(3),
    QBSTEP NUMERIC(3),
    QBLEVEL NUMERIC(3),
    QBTIME DATE DEFAULT SYSDATE,
    FOREIGN KEY (AID) REFERENCES ADMIN(AID),
    FOREIGN KEY (MID) REFERENCES MEMBER(MID)
    );
    
commit;
    
    
---------------------------------장바구니 테이블 생성-----------------------
DROP TABLE BASKET cascade Constraints;
DROP SEQUENCE BASKET_SEQ;
CREATE SEQUENCE BASKET_SEQ;
CREATE TABLE BASKET(      
    BNO NUMBER(5),
    MID VARCHAR2(20),
    PID VARCHAR2(30),
    BCOUNT NUMERIC(3),
    BTOTAL NUMERIC(9),
    Primary key(BNO,MID),
    FOREIGN KEY (MID) REFERENCES MEMBER(MID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
    );

---------------------------------최근본 제품 테이블 생성-----------------------     
DROP TABLE CURRENTPRODUCT cascade Constraints;    
drop sequence CURRENTPRODUCT_SEQ;
CREATE SEQUENCE CURRENTPRODUCT_SEQ;
CREATE TABLE CURRENTPRODUCT(
    Currid number(30),
    MID VARCHAR2(20),
    PID VARCHAR2(30),
    CTIME DATE DEFAULT SYSDATE,
    FOREIGN KEY(MID) REFERENCES MEMBER(MID),
    FOREIGN KEY(PID) REFERENCES PRODUCT(PID),
    PRIMARY KEY (Currid)
    );
    
    
---------------------------------주문-----------------------     
DROP TABLE ORDERS cascade Constraints;
CREATE TABLE ORDERS(
    ONO VARCHAR2(20) PRIMARY KEY,
    MID VARCHAR2(20) NOT NULL,
    ODATE DATE DEFAULT SYSDATE,
    OADDRESS VARCHAR2(255) NOT NULL,
    OPHONE VARCHAR2(30),
    OCOMPLETEALL NUMBER(2) DEFAULT 0,  -- 주문 완료를 위해서 추가 했음
    FOREIGN KEY (MID) REFERENCES MEMBER(MID)
    );
    
---------------------------------주문내역-----------------------  
DROP TABLE ORDER_DETAIL cascade Constraints;
CREATE TABLE ORDER_DETAIL(
    ONO VARCHAR2(20),
    PID VARCHAR2(30),
    QTY NUMERIC(3),
    TOTALPRICE NUMERIC(8),
    OCOMPLETEONE NUMBER(2) DEFAULT 0,  -- 주문 완료를 위해서 추가했음
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID),
    PRIMARY KEY (ONO, PID)
    );
    
---------------------------------예약----------------------- 
DROP TABLE RESERVATION cascade Constraints;
CREATE TABLE RESERVATION(    
    ONO VARCHAR2(20) PRIMARY KEY,
    OSHIPDATE VARCHAR2(30),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO)
    );
    
---------------------------------TEST------------------------------------------

--발표셋팅을 위함--
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '감바스 알 아히요', 500, '', 15000, '', 0,'감바스 알 아히요.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '구운채소샐러드', 450, '', 25000, '', 0,'구운채소샐러드.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '그랑씨엘 치아바타', 600, '', 15000, '', 0,'그랑씨엘 치아바타.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '냉이된장리조또', 450, '', 25000, '', 0,'냉이된장리조또.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '닭가슴살스테이크', 300, '', 15000, '', 0,'닭가슴살스테이크.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '닭녹두죽', 350, '', 15000, '', 0,'닭녹두죽.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '도토리묵', 400, '', 10000, '', 0,'도토리묵.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '돼지고기 수육', 450, '', 25000, '', 0,'돼지고기 수육.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '명란젓', 450, '', 15000, '', 0,'명란젓.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '무말랭이무침', 450, '', 25000, '', 0,'무말랭이무침.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '무쌈말이', 300, '', 10000, '', 0,'무쌈말이.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '밀푀유 나베', 750, '', 25000, '', 0,'밀푀유 나베.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '베트남 쌀국수', 550, '', 15000, '', 0,'베트남 쌀국수.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '봄동 원팟파스타', 650, '', 25000, '', 0,'봄동 원팟파스타.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '샤브샤브 국수', 700, '', 15000, '', 0,'샤브샤브 국수.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '서울식 불고기 전골', 850, '', 25000, '', 0,'서울식 불고기 전골.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소갈비찜', 900, '', 45000, '', 0,'소갈비찜.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기 고추잡채', 650, '', 25000, '', 0,'소고기 고추잡채.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기 떡국', 600, '', 25000, '', 0,'소고기 떡국.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기 버섯 잡채', 550, '', 15000, '', 0,'소고기 버섯 잡채.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기 버섯 잡채볶음', 600, '', 15000, '', 0,'소고기 버섯 잡채볶음.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '소고기야채죽', 450, '', 15000, '', 0,'소고기야채죽.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '수제카레', 550, '', 10000, '', 0,'수제카레.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '쉬림프 로제 파스타', 650, '', 15000, '', 0,'쉬림프 로제 파스타.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '쉬림프 타코', 600, '', 15000, '', 0,'쉬림프 타코.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '비프 퀘사디아', 450, '', 15000, '', 0,'비프 퀘사디아.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '시그니처 스테이크', 550, '', 25000, '', 0,'시그니처 스테이크.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '아삭감자샐러드.JPG', 450, '감자', 10000, '', 0,'아삭감자샐러드.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '연포탕', 600, '', 15000, '', 0,'연포탕.jpg',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '우엉덮밥', 450, '', 15000, '', 0,'우엉덮밥.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '닭가슴살 샐러드', 600, '', 15000, '', 0,'닭가슴살 샐러드.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '이차돌박이 겉절이', 450, '', 15000, '', 0,'이차돌박이 겉절이.JPG',100,1);


INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '일본식 냉우동', 600, '', 15000, '', 0,'일본식 냉우동.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '주꾸미 오일 파스타', 450, '', 15000, '', 0,'주꾸미 오일 파스타.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '차돌 된장찌개', 600, '', 15000, '', 0,'차돌 된장찌개.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '캐슈넛멸치볶음', 450, '', 15000, '', 0,'캐슈넛멸치볶음.JPG',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '콩나물 삽겹살 짜글이', 600, '', 15000, '', 0,'콩나물 삽겹살 짜글이.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '투움바 파스타', 450, '', 15000, '', 0,'투움바 파스타.jpg',100,1);

INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMDPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '한방갯벌장어죽', 600, '', 15000, '', 0,'한방갯벌장어죽.JPG',100,1);
INSERT INTO PRODUCT(PID, PNAME, PCAL, PMAIN, PPRICE, PCONTENT, PHIT,PIMAGE,PSTOCK,PMEGAPICK) VALUES(PRODUCT_SEQ.NEXTVAL, '베이컨 파스타', 450, '', 15000, '', 0,'베이컨 파스타.JPG',100,1);

COMMIT;

UPDATE PRODUCT SET PMAIN='새우', PCONTENT='작은 냄비라는 뜻의 까수엘라 라고도 불리는 감바스는 대표적인 스페인 요리' WHERE PNAME='감바스 알 아히요';
UPDATE PRODUCT SET PMAIN='버섯', PCONTENT='야외 바비큐 때 고기 메뉴와 함께 준비하면 완벽한 궁합을 자랑할 구운 채소 샐러드' WHERE PNAME='구운채소샐러드';
UPDATE PRODUCT SET PMAIN='빵', PCONTENT='프렙의 베이커리 전문가들이 직접 만드는 100%수제 빵' WHERE PNAME='그랑씨엘 치아바타';
UPDATE PRODUCT SET PMAIN='된장', PCONTENT='냉이향이 짙은 소고기냉이 된장찌개' WHERE PNAME='냉이된장리조또';
UPDATE PRODUCT SET PMAIN='닭가슴살', PCONTENT='닭가슴살의 고단백질을 이용한 샐러드' WHERE PNAME='닭가슴살 샐러드';
UPDATE PRODUCT SET PMAIN='닭가슴살', PCONTENT='닭가슴살을 이용한 저칼로리 스테이크' WHERE PNAME='닭가슴살스테이크';
UPDATE PRODUCT SET PMAIN='닭', PCONTENT='녹두를 이용한 닭죽' WHERE PNAME='닭녹두죽';
UPDATE PRODUCT SET PMAIN='묵', PCONTENT='특유의 매콤새콤한 맛의 도토리묵' WHERE PNAME='도토리묵';
UPDATE PRODUCT SET PMAIN='돼지고기', PCONTENT='고기와 야채를 듬뿍 넣어 자작하게 끓여낸 짜글이' WHERE PNAME='돼지고기 짜글이';
UPDATE PRODUCT SET PMAIN='명란', PCONTENT='밥도둑 명란젓' WHERE PNAME='명란젓';
UPDATE PRODUCT SET PMAIN='무', PCONTENT='꼬들꼬들하게 말린 무말랭이를 맛깔스러운 양념에 버무림' WHERE PNAME='무말랭이무침';
UPDATE PRODUCT SET PMAIN='무', PCONTENT='파프리카의 아삭한 식감, 쌈무와 머스타도 소스의 새콤달콤함' WHERE PNAME='무쌈말이';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='프랑스어로 천겹의 잎사귀라는 뜻의 퓨전 일본식 전골' WHERE PNAME='밀푀유 나베';
UPDATE PRODUCT SET PMAIN='베이컨', PCONTENT='베이컨이 들어간 파스타' WHERE PNAME='베이컨 파스타';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='베트남 전통의 국수' WHERE PNAME='베트남 쌀국수';
UPDATE PRODUCT SET PMAIN='봄동', PCONTENT='비타민이 골고루 들어있는 봄나물을 이용한 파스타' WHERE PNAME='봄동 원팟파스타';
UPDATE PRODUCT SET PMAIN='치즈', PCONTENT='멕시코를 대표하는 요리' WHERE PNAME='비프 퀘사디아';
UPDATE PRODUCT SET PMAIN='국수', PCONTENT='튀기지 않은 생면을 이용해 조리하는 샤브샤브 국수' WHERE PNAME='샤브샤브 국수';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='감칠맛을 입은 부드러운 소불고기와 각종 버섯이 어우러짐' WHERE PNAME='서울식 불고기 전골';
UPDATE PRODUCT SET PMAIN='소갈비', PCONTENT='소갈비와 표고버섯, 월계수잎 등을 이용한 소갈비찜' WHERE PNAME='소갈비찜';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='소고기와 매콤하고 아삭한 야채를 볶은 중화요리' WHERE PNAME='소고기 고추잡채';
UPDATE PRODUCT SET PMAIN='떡', PCONTENT='소고기가 들어간 떡국' WHERE PNAME='소고기 떡국';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='고소한 소고기와 향긋한 버섯을 넣은 잡채' WHERE PNAME='소고기 버섯 잡채';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='고소한 소고기와 향긋한 버섯을 넣고 볶은 잡채' WHERE PNAME='소고기 버섯 잡채볶음';
UPDATE PRODUCT SET PMAIN='죽', PCONTENT='소고기를 넣은 건강하고 맛있는 야채죽' WHERE PNAME='소고기야채죽';
UPDATE PRODUCT SET PMAIN='카레', PCONTENT='국산 돼지고기와 감자, 양파, 당근을 넣은 카레' WHERE PNAME='수제카레';
UPDATE PRODUCT SET PMAIN='파스타', PCONTENT='빨간 토마토소스와 크림 소스가 만난 장밋빛 로제파스타' WHERE PNAME='쉬림프 로제 파스타';
UPDATE PRODUCT SET PMAIN='새우', PCONTENT='고수를 얇게 썰어 넣은 쉬림프 타코' WHERE PNAME='쉬림프 타코';
UPDATE PRODUCT SET PMAIN='소고기', PCONTENT='적절한 마블링을 함유한 스테이크' WHERE PNAME='시그니처 스테이크';
UPDATE PRODUCT SET PMAIN='감자', PCONTENT='사이드 디쉬로 곁들여먹기 좋은 아삭한 감자샐러드' WHERE PNAME='아삭감자샐러드';
UPDATE PRODUCT SET PMAIN='낙지', PCONTENT='맑은 국물에 신선한 낙지를 그대로 끓여낸 연포탕' WHERE PNAME='연포탕';
UPDATE PRODUCT SET PMAIN='우엉', PCONTENT='간장에 졸인 우엉을 곁들인 우엉덮밥' WHERE PNAME='우엉덮밥';
UPDATE PRODUCT SET PMAIN='주꾸미', PCONTENT='올리브 오일에 주꾸미, 마늘, 페퍼가 어우러진 파스타' WHERE PNAME='주꾸미 오일 파스타';
UPDATE PRODUCT SET PMAIN='된장', PCONTENT='직접만든 된장 양념장과 풍미 가득한 차돌을 넣어 고소함과 구수함 깊은맛의 된장찌개' WHERE PNAME='차돌 된장찌개';
UPDATE PRODUCT SET PMAIN='멸치', PCONTENT='고소한 캐슈넛을 넣은 멸치볶음' WHERE PNAME='캐슈넛멸치볶음';
UPDATE PRODUCT SET PMAIN='돼지고기', PCONTENT='삼겹살을 넣은 짜글이 찌개에 콩나물을 곁들여 깊은 맛을 낸 콩나물 삼겹살 짜글이' WHERE PNAME='콩나물 삽겹살 짜글이';
UPDATE PRODUCT SET PMAIN='파스타', PCONTENT='넓적한 페투니치면에 촘촘히 배어든 크림소스의 풍미가 일품인 투움바 파스타' WHERE PNAME='투움바 파스타';
UPDATE PRODUCT SET PMAIN='장어', PCONTENT='강화도 산 갯벌장어를 갈아 만들은 한방갯벌장어죽' WHERE PNAME='한방갯벌장어죽';
